doctrine_migrations:
  migrations_paths:
    'App\Migrations': '%kernel.project_dir%/src/Migrations'

  storage:
    # Default (SQL table) metadata storage configuration
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 192
      executed_at_column_name: 'executed_at'

  # Entity manager to use for migrations. This overrides the "connection" setting.
  em: default

  # Run all migrations in a transaction.
  all_or_nothing: true